packages:
  - packages/backend
  - packages/configs
  - packages/frontend

catalog:
  '@types/node': '~22.13.10'
  '@types/web': '0.0.212'
  eslint: '~9.22.0'
  jiti: '~2.4.2'
  prettier: '~3.5.3'
  typescript: '~5.8.2'
  'typescript-eslint': '~8.26.1'
